version: "3"
services:
    app_service:
        build: ./app_service
        ports:
            - "5000:5000"
        depends_on:
            - prometheus
    model_service:
        build: ./model_service
        ports:
            - "5001:5001"
        depends_on:
            - prometheus
    prometheus:
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes:
          - ./prometheus:/etc/prometheus
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
